services:
  - type: web
    name: stock-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FINNHUB_API_KEY
        value: 8aa76e8d52914c9f9b0e8893f6c17012
